---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to our research website.

### What is Virtual reality (VR) ?

Virtual reality (VR) can be characterized by the following:
"Virtual Reality (VR) is a computer-generated reality with images (3D) and, in many cases, sound. It is transmitted via large screens, in special rooms (Cave Automatic Virtual Environment, CAVE for short) or via a head-mounted display (video or VR glasses)." (Bendel, 2018). Here, the illusion of participating in a synthetic environment is created instead of merely observing it from the outside (Earnshaw, 1993).
Advantages of VR can already be partly inferred from the definition. For example, the high flexibility in adaptation and controllability of the synthetic and interactive intervention, the relatively low level of therapist involvement required, and the general "low cost" and wide availability make VR an interesting and novel therapeutic option outside of experimental laboratories (Freeman et al., 2017; Riva, 2005).
One of the most important advantages, which will be discussed in more detail here and to which this study will contribute, is the synthetic environment. It provides the opportunity to incorporate and directly address social influence and pressure, as well as other environmental influences. Situations can be created, whose real circumstance would be immoral or illegal. In addition to the synthetic world and realistic representation, VR goggles can be used to shield external visual stimuli that can be distracting. The representation of the environment and objects within VR is possible in 3D. A 3D representation provides a more realistic presentation of the objects triggering craving and behavioral tendencies. In terms of implicit cognitions associated with AKS, this could offer a therapeutic advantage. From the combination of VR and different testing paradigms, there is also the advantage, compared to the classical variants, that the playful character of these methods can lead to an increased motivation of the subjects (Mostajeran, Kirsten, Steinicke, Gallinat, & Kuhn, 2019). In psychotherapy, VR has been used primarily in the treatment of anxiety disorders. Among these were promising intervention studies for PTSD (Freeman et al., 2017; Riva, 2005). As described in the previous chapter, comorbid disorders also have an impact on AKS. VR is already used for a wide variety of substance dependencies such as cocaine, tobacco, and alcohol (Durl, Dietrich, Pang, Potter, & Carter, 2018; Ghiţă et al., 2019; Kim & Lee, 2015; Maples-Keller, Bunnell, Kim, & Rothbaum, 2017; Mostajeran et al., 2019; Pericot-Valverde, Secades-Villa, Gutiérrez-Maldonado, & García-Rodríguez, 2014; Saladin, Brady, Graap, & Rothbaum, 2006). Previous studies primarily use cue exposure therapy (CET), focusing primarily on patients' craving (Hone-Blanchet, Wensing, & Fecteau, 2014; Lee, Kwon, Choi, & Yang, 2007; Pelissolo, Abou Kassm, & Delhay, 2019).  However, for alcohol addiction and other substance use disorders, CET showed limited effects. In terms of alcohol use reduction, AAT interventions have shown more promising clinical results than CET (Eberl et al., 2013; Manning et al., 2016; Reinout W. Wiers et al., 2011).  If conventional methods targeting craving can be enhanced by VR (Ghiţă & Gutiérrez-Maldonado, 2018), the question is whether adding VR to an Approach Avoidance Training Program (AATP) can increase the effectiveness of this approach. The versatility of its application to a wide variety of disorders also makes VR an interesting therapeutic extension for AKS. Initial studies have already demonstrated potential effects of the Virtual Alcohol AAT (VR-A-AAT) (Kim & Lee, 2015). Simulating a wider range of stimuli and other trigger stimuli , than is otherwise possible in clinical treatment settings (Ghiţă & Gutiérrez-Maldonado, 2018). The research and practice of using meaningful pictorial representations of alcoholic and non-alcoholic beverages in the VR-A-AAT should benefit from this study.


